name: lint and prettier code

env:
  BACKEND: "./project/backend"

on:
  push:
    branches:
      - "**" # two wildcards make sure branches with a slash in them also get matched, f.e. feature/game

jobs:
  prettier:
    name: Run ESLint
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ${{ env.BACKEND }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with auto-fix
        run:  exit 1

      - name: just test
        run:  echo hi
